-- MySQL Script generated by MySQL Workbench
-- 11/07/16 13:19:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myhospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myhospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myhospital` DEFAULT CHARACTER SET utf8 ;
USE `myhospital` ;

-- -----------------------------------------------------
-- Table `myhospital`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`hospital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `hospital_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `departmentHospital_FK`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `myhospital`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `birth` DATE NULL,
  `issue` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`diagnosis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diagnosis_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_diagnosis_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `myhospital`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `diagnosis_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_patient_department1_idx` (`department_id` ASC),
  INDEX `fk_patient_person1_idx` (`person_id` ASC),
  INDEX `fk_patient_diagnosis1_idx` (`diagnosis_id` ASC),
  CONSTRAINT `fk_patient_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `myhospital`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `myhospital`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_diagnosis1`
    FOREIGN KEY (`diagnosis_id`)
    REFERENCES `myhospital`.`diagnosis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `education` VARCHAR(45) NULL,
  `contract` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `department_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC),
  INDEX `fk_employee_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `myhospital`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `myhospital`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`nurse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `employee_person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_person_id`),
  INDEX `fk_nurse_employee1_idx` (`employee_id` ASC, `employee_person_id` ASC),
  CONSTRAINT `fk_nurse_employee1`
    FOREIGN KEY (`employee_id` , `employee_person_id`)
    REFERENCES `myhospital`.`employee` (`id` , `person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `patient_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `nurse_id` INT NOT NULL,
  `nurse_employee_id` INT NOT NULL,
  `nurse_employee_person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_patient1_idx` (`patient_id` ASC),
  INDEX `fk_room_department1_idx` (`department_id` ASC),
  INDEX `fk_room_nurse1_idx` (`nurse_id` ASC, `nurse_employee_id` ASC, `nurse_employee_person_id` ASC),
  CONSTRAINT `fk_room_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `myhospital`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `myhospital`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_nurse1`
    FOREIGN KEY (`nurse_id` , `nurse_employee_id` , `nurse_employee_person_id`)
    REFERENCES `myhospital`.`nurse` (`id` , `employee_id` , `employee_person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myhospital`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myhospital`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `license` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  `employee_person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_person_id`),
  INDEX `fk_doctor_employee1_idx` (`employee_id` ASC, `employee_person_id` ASC),
  CONSTRAINT `fk_doctor_employee1`
    FOREIGN KEY (`employee_id` , `employee_person_id`)
    REFERENCES `myhospital`.`employee` (`id` , `person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
